### ISSUE TITLE
none of the options for setting host, username, password, alternate conf, etc. work

### ISSUE THREAD

**Issue by TalkData2Me** [capitalone/giraffez#8] opened 2016-09-23 23:50 UTC
I need a way to pass credentials into the ```cmd.execute``` statement without writing them out to ```.girafferc```. The documentation indicates that it should be possible to do this, but it doesn't seem to be working (e.g. ```giraffez cmd --help``` doesn't list setting these parameters as options, despite what the documentation says).

**Comment by ktravis** [comment] 2016-09-24 01:13
Do you mean you are trying to override the `.girafferc` credentials while using `Cmd` in the Python API? What have you tried, and what was the result?

`giraffez cmd --help` doesn't list username or password because there aren't command line flags for specifying those. This was a conscious decision to avoid encouraging users to hard-code their passwords into scripts, but I would be interested to hear a case for it if there is one. I could see this maybe being useful if there are situations where a configuration file can't be written or is undesirable -- I just haven't run into them myself.

Also, if you could point me to what part of the documentation was misleading, it may be outdated and I would like to correct it.

**Comment by TalkData2Me** [comment] 2016-09-24 01:39
I have a process that needs to live in a shared environment with no separate user-specific spaces but concurrent use by different users. Ideally, I want to be able to define the host in the ```.girafferc``` while leaving the username and password null and then use raw_input() to have users input their credentials. Agree that credentials shouldn't be hard-coded, but that's more on the user than on the tool to enforce.

Here's what I've tried and why:
* I tried ```giraffez.Export(query='some sql',host='myDB',username='abc',password='xyz')``` (with and without the host parameter) because [this part](http://www.capitalone.io/giraffez/api.html#module-giraffez.export) of the documentation says it's possible. Python modules that are documented to take username/password are [cmd](http://www.capitalone.io/giraffez/api.html#module-giraffez.cmd), [export](http://www.capitalone.io/giraffez/api.html#module-giraffez.export), [load](http://www.capitalone.io/giraffez/api.html#module-giraffez.load), and [mload](http://www.capitalone.io/giraffez/api.html#module-giraffez.mload).
* I also tried stuff like:
    ```

with giraffez.Config() as conf:
        conf.set_value('username','abc')
        conf.set_value('password','xyz')
        print conf.list_value()
        with giraffez.Cmd() as cmd:
            result = cmd.execute(query="some sql",config=conf)
   ``` 
where the ```conf.set_value``` actually does work, but I couldn't find a way to pass that into an execute statement without writing to file.
* Lastly, I tried command line stuff like ```giraffez cmd "some sql" --host myDB --username abc --password xyz``` the [Command Line documentation](http://www.capitalone.io/giraffez/command-line.html) states "There are certain shared options that any of the following commands will receive:" and subsequently lists username, password, host, and conf.

**Comment by ktravis** [comment] 2016-09-26 14:33
What are the results you're getting with the Python API example (passing in host/username/password to Export constructor)? I'm not having any issues running that on my end (with no configuration file, and with one that is effectively empty). 

If you could please provide:
- a minimal (but complete) script that fails
- pertinent environment information (platform, Teradata library version, python version, and anything else that might be relevant for reproducing the issue)
- the output/errors you're seeing

that would be extremely helpful.

For your example with setting the values in the configuration directly, there is currently not an option for passing in a `Config` object, as the config would be needed at the time of instantiation and all of the options that would be used are available as keyword arguments. There is a `config` keyword argument which allows passing in an alternate config file location to read from, but that wouldn't accomplish what you are looking for.

Thanks for pointing out that discrepancy -- depending on how we decide to resolve the issue, that will be fixed.

**Closed** 2016-09-28 21:12 UTC

**Comment by ktravis** [comment] 2016-09-28 21:17
I've adjusted the docs for the command line to reflect the fact that username, password, and host cannot be overridden, as you pointed out.

If you have the additional information above I would be glad to reopen the issue and try to help further. By design and in our own testing, directly specifying host, username, and password to the constructors for both `Cmd` and `Export` should be functioning properly (whether or not you have a `.girafferc`. If you are experiencing otherwise there may be some issue with the environment, or with your script, that is affecting things.

**Comment by ChrisRx** [comment] 2016-10-03 14:29
I am putting this reply in here for more context in case someone comes across this issue.

I'm sorry to hear that it wasn't working for you and I hope that the lack of response is because it is now working, but please speak up if this is not the case.

I did want to mention that the `giraffez.Config` is not like a "runtime" configuration rather an abstraction around serializing the `.girafferc`, which is why it reads it once at the beginning rather than trying to read this information continuously as you use the Python API.  Generally speaking, you wouldn't want to use `giraffez.Config` in your scripts unless that script was meant to modify the information in `.girafferc` and then persist to disk.

I disagree with the notion that security is only enforced by the user, and feel strongly that good security practices should be observed at every level whether it be those designing software or those using it.  I didn't, however, want this to be a reason to impede the users ability and because of that we worked on providing as many easy-to-use/safe alternatives for configuring this information.  This is why there are numerous options to set the connection information:
* automatically read from `.girafferc`
* alternative `.girafferc`/`.giraffepg` passed to command-line via `--key/--conf`
* alternative `.girafferc`/`.giraffepg` with the Python API via keyword parameters `key` and `conf`
* expressly passing in `host`, `username`, and `password` to any `giraffez.Connection` subclass
* having multiple connections in `.girafferc` and specifying the connection via `--dsn` on the command-line or with the `dsn` keyword parameter

Passing around sensitive information, specifically the username/password, was not something that I wanted to be available to the command-line.  Environments with many users are able to easily see these values as they are running (e.g. `ps aux`) and this information also persists in command history files unencrypted (e.g. `.bash_history`).  I recognize that this may be a desired feature but the alternatives provided were designed to fill this gap.  If there are suggestions for other secure means of handling connection information that we could include, please let us know so that can be considered and added (or contributed by yourself or others!).
