### ISSUE TITLE
coperr.h file not found

### ISSUE THREAD

**Issue by evanfwelch** [capitalone/giraffez#29] opened 2017-03-14 16:07 UTC
I have Mac OS X, Python 3.5

I cloned the repo and checked out 2.0.0. After running python setup.py install I got this error:

```
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/frw169/anaconda/include -arch x86_64 -I/Users/frw169/CODE/giraffez/giraffez -I/Users/frw169/anaconda/include/python3.5m -c giraffez/src/columns.c -o /Users/frw169/CODE/giraffez/build/giraffez/src/columns.o -Wfatal-errors
In file included from giraffez/src/columns.c:18:
In file included from giraffez/src/giraffez.h:30:
giraffez/src/teradata.h:44:10: fatal error: 'coperr.h' file not found
#include <coperr.h>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
```

For me, I find this coperr.h file in opt/teradata/client/16.00/include/coperr.h. Are there any environmental variables that need to be set? I'm currently having no trouble running the master branch (v 1.1.8)

**Comment by ChrisRx** [comment] 2017-03-14 20:23
Closing because environment configuration problem, likely caused by having a incomplete installation of a newer version.

**Closed by ChrisRx** 2017-03-14 20:23 UTC

**Comment by wxianxin** [comment] 2018-09-06 15:26
I don't wanna reopen this but it is indeed a frequent problem. Constantly showing on Mac OS. It does not have to be user's responsibility to fix this.
